# Project: testpkcs
# Makefile created by Dev-C++ 5.15

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = pkcs7-gen.o
LINKOBJ  = pkcs7-gen.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc libcrypto.a libssl.a "C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libws2_32.a" -m64 -g3
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.7.2/include/c++"
BIN      = testpkcs.exe
CXXFLAGS = $(CXXINCS) -O3 -m64 -g3
CFLAGS   = $(INCS) -O3 -m64 -g3
RM       = del /q

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

pkcs7-gen.o: pkcs7-gen.cpp
	$(CPP) -c pkcs7-gen.cpp -o pkcs7-gen.o $(CXXFLAGS)
